import turtle 
import random
color=random.choice
# setup turtle window
t = turtle.Turtle()
t.shape("turtle")
color = random.choice(["red","yellow","green","blue","purple","pink","black","White","brown","gray"])
turtle.bgcolor(color)
t.pensize(2)
t.color("orange")
t.speed(10)
# draw and move turtle 
#length = float(input("Enter your length:"))
length = turtle.textinput("Window","Enter Your Distance")
length = int(length)
angel = turtle.textinput("Window","Enter your Angel")
angel = int(angel)
color = random.choice(["red","yellow","green","blue","purple","pink","black","White","brown","gray"])
t.begin_fill()
t.color(color)
t.forward(length)
t.left(angel)
t.forward(length)
t.left(angel)
t.forward(length)
t.left(angel)
t.forward(length)
t.end_fill()
t.write(f"perimiter={length*4}",font=("Areal",14,"normal"))
t.penup()
t.forward(50)
t.pendown()
t.write(f"square={length*length}",font=("Areal",14,"normal"))
# Draw Triangel
t.penup()
t.forward(100)
t.left(90)
t.pendown()
t.begin_fill()
t.forward(100)
t.left(120)
t.forward(100)
t.left(120)
t.forward(100)
t.end_fill()
turtle.exitonclick()